name: Create Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create downloads.zip
      run: |
        zip -j downloader.zip download.json dw.pygame
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: downloader.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}